# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/JAMK-IT/IIO12200-ohjelmistoprojekti/wiki
title: Templaattikurssi
email: your-email@domain.com
author: JAMK-IT
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016. &nbsp; Project maintained by JAMK-IT. &nbsp; Hosted on GitHub Pages.'
credits: 'Credits: Open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: wiki
    url: https://github.com/JAMK-IT/IIO12200-ohjelmistoprojekti/wiki
    icon: fa fa-github fa-fw
  - title: code
    url: https://github.com/JAMK-IT/IIO12200-ohjelmistoprojekti
    icon: fa fa-github fa-fw
  - title: asio
    url: https://asio.jamk.fi/pls/asio/asio_ectskuv1.kurssin_ks?ktun=IIO12200&knro=&noclose=%20&lan=e
    icon: fa fa-file fa-fw
  - title: tilaajaksi?
    url: https://asio.jamk.fi/pls/asio/asio_ectskuv1.kurssin_ks?ktun=IIO12200&knro=&noclose=%20&lan=e
    icon: fa fa-file fa-fw
